# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Imad Berrouyne
name: Imad Berrouyne
email: imad.berrouyne@uni.lu
description: >- # this means to ignore newlines until "baseurl:"
  Researcher in Computer Science
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: imberrou
github_username:  imberrou
content:
  description:  I am a postdoctoral researcher in the [Interdisciplinary Centre for Security, Reliability and Trust (SnT)](https://wwwfr.uni.lu/snt) at the [University of Luxembourg](https://wwwfr.uni.lu). I received a double Ph.D. degree from the [Université du Québec à Chicoutimi](https://www.uqac.ca/) and [Institut Mines Télécom Atlantique](https://www.imt-atlantique.fr/) (IMT Atlantique) under the supervision of Jean-Claude Royer, [Massimo Tisi](https://massimotisi.github.io/), [Mehdi Adda](https://www.uqar.ca/universite/a-propos-de-l-uqar/departements/departement-de-mathematiques-informatique-et-genie/adda-mehdi) and [Jean-Marie Mottu](http://pagesperso.ls2n.fr/~mottu-jm/research-en.html). I developed a software methodology based on Model-Driven Engineering (MDE) to overcome heterogeneity challenges in the IoT. Before my Ph.D., I obtained a Bachelor degree in computer science and a Master degree in computer networking from the [Université Claude Bernard Lyon 1](https://www.univ-lyon1.fr/).

# Build settings
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
hard_wrap: true